### ISSUE TITLE
mptcp_trunk doesn't build with CONFIG_MEMCG

### ISSUE THREAD

**Issue by teto** [multipath-tcp/mptcp#308]
Hi,

I am trying to compile the kernel with the netlink patch (v5) which implies to run mptcp_trunk (a221796c2cde86d3be226c4ea4997e0f1aefd33c).

In my config, I enable 
```
CONFIG_MEMCG=y
CONFIG_MEMCG_SWAP=y
CONFIG_MEMCG_SWAP_ENABLED=y
CONFIG_MEMCG_KMEM=y
```

```

../net/ipv4/tcp_ipv4.c:2587:3: error: 'struct proto' has no member named 'init_cgroup'
  .init_cgroup  = tcp_init_cgroup,
   ^~~~~~~~~~~
../net/ipv4/tcp_ipv4.c:2587:18: error: 'tcp_init_cgroup' undeclared here (not in a function); did you mean 'tcp_init_cwnd'?
  .init_cgroup  = tcp_init_cgroup,
                  ^~~~~~~~~~~~~~~
                  tcp_init_cwnd
../net/ipv4/tcp_ipv4.c:2587:18: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
../net/ipv4/tcp_ipv4.c:2587:18: note: (near initialization for 'tcp_prot')
../net/ipv4/tcp_ipv4.c:2588:3: error: 'struct proto' has no member named 'destroy_cgroup'; did you mean 'destroy'?
  .destroy_cgroup  = tcp_destroy_cgroup,
   ^~~~~~~~~~~~~~
   destroy
  CC [M]  sound/usb/line6/driver.o
../net/ipv4/tcp_ipv4.c:2588:21: error: 'tcp_destroy_cgroup' undeclared here (not in a function); did you mean 'tcp_init_cgroup'?
  .destroy_cgroup  = tcp_destroy_cgroup,
                     ^~~~~~~~~~~~~~~~~~
                     tcp_init_cgroup
../net/ipv4/tcp_ipv4.c:2588:21: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
../net/ipv4/tcp_ipv4.c:2588:21: note: (near initialization for 'tcp_prot')
../net/ipv4/tcp_ipv4.c:2589:3: error: 'struct proto' has no member named 'proto_cgroup'
  .proto_cgroup  = tcp_proto_cgroup,
   ^~~~~~~~~~~~
../net/ipv4/tcp_ipv4.c:2589:19: error: 'tcp_proto_cgroup' undeclared here (not in a function); did you mean 'tcp_init_cgroup'?
  .proto_cgroup  = tcp_proto_cgroup,
                   ^~~~~~~~~~~~~~~~
                   tcp_init_cgroup
../net/ipv4/tcp_ipv4.c:2589:19: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
../net/ipv4/tcp_ipv4.c:2589:19: note: (near initialization for 'tcp_prot')
  CC [M]  fs/nls/nls_cp949.o


```
Seems like tcp_init_cgroup was introduced in 5c3675582cbbdc99f720aa1dcc1821e26c2be1ab and implemented in tcp_memcontrol.c which does not exist anymore. Not sure what to do as ideally I would like to keep CONFIG_MEMCG.

NB: I also had to disable CRYPTO_DEV_CHELSIO which triggered compilation errors.

**Comment by matttbe** [comment]
Hi Matthieu,

Thank you for testing the new Netlink PM.

Mmh, strange, this part of the code should be removed :-/
See baac50bbc3cdfd184ebf586b1704edbfcee866df
I don't have more explanation with a git blame: https://github.com/multipath-tcp/mptcp/blame/mptcp_trunk/net/ipv4/tcp_ipv4.c#L2586

I guess a merge conflict was not solved correctly. I can have a look.

Feel free to report any bug or improvement to do related to MPTCP and this new Netlink PM ;-)

Matthieu

**Comment by teto** [comment]
That would be really cool if you could have a look. Btw I suppose there is no opensource userspace client matching the netlink module ? I've started writing one, hence the question.

**Comment by matttbe** [comment]
> Btw I suppose there is no opensource userspace client matching the netlink module ? I've started writing one, hence the question.

Intel is going to release one soon, they got the approval in [December](https://lists.01.org/pipermail/mptcp/2018-December/000952.html) but the code still need to be reviewed, etc.
I guess it is always good to have different open-source prototypes :)

**Comment by teto** [comment]
great news. My path manager is written in haskell so I am pretty confident there will be at least this difference :) 
Looking forward to a fix on mptcp_trunk. Or do you think the patch applies on 0.94 ? maybe I should give it a try (IIRC it didn't work)

**Comment by matttbe** [comment]
I just sent a small patch on mptcp-dev for this issue.

May you validate that it is OK on your side? :)

``` patch
diff --git a/net/ipv4/tcp_ipv4.c b/net/ipv4/tcp_ipv4.c
index 9a45fd8e2aa3..6ce7280e215f 100644
--- a/net/ipv4/tcp_ipv4.c
+++ b/net/ipv4/tcp_ipv4.c
@@ -2582,11 +2582,6 @@ struct proto tcp_prot = {
 #ifdef CONFIG_COMPAT
        .compat_setsockopt      = compat_tcp_setsockopt,
        .compat_getsockopt      = compat_tcp_getsockopt,
-#endif
-#ifdef CONFIG_MEMCG_KMEM
-       .init_cgroup            = tcp_init_cgroup,
-       .destroy_cgroup         = tcp_destroy_cgroup,
-       .proto_cgroup           = tcp_proto_cgroup,
 #endif
        .diag_destroy           = tcp_abort,
 #ifdef CONFIG_MPTCP
```

> My path manager is written in haskell so I am pretty confident there will be at least this difference :)

I am pretty sure it will be different then :-)

> Or do you think the patch applies on 0.94 ? maybe I should give it a try (IIRC it didn't work)

Some small adaptations will need to be done (due to the use of lockless subflows in mptcp_trunk). But it is not planned for us to backport it on this branch as it is a new feature ;-)

**Comment by teto** [comment]
thansk this has solved it. I now have 
```
ERROR: "tcp_send_active_reset" [net/mptcp/mptcp_netlink.ko] undefined!
ERROR: "mptcp_hash_find" [net/mptcp/mptcp_netlink.ko] undefined!
```
with the v5. Will try the v6.

**Comment by matttbe** [comment]
> with the v5. Will try the v6.

yes, it is fixed with the v6. But better to directly switch to the v7 ;-)

**Comment by teto** [comment]
I don't want to open a new issue for something this trivial but I don't see MPTCP options on local connections (iperf on localhost for instance) while it works just fine outside (even with debug sysctl). Do you have any idea what could cause such behavior ? I see this with mptcp_trunk but it was the same with 0.94.

Btw a patch to silence some warnings https://github.com/multipath-tcp/mptcp/compare/mptcp_trunk...teto:trunk_v8?expand=1

**Comment by matttbe** [comment]
> I don't want to open a new issue for something this trivial but I don't see MPTCP options on local connections (iperf on localhost for instance) while it works just fine outside (even with debug sysctl). Do you have any idea what could cause such behavior ? I see this with mptcp_trunk but it was the same with 0.94.

Yes, loopback interfaces are filtered in the Fullmesh PM (see `addr[46]_event_handler()`). It doesn't make sense to have MPTCP overhead for a one path and local connections.

> Btw a patch to silence some warnings https://github.com/multipath-tcp/mptcp/compare/mptcp_trunk...teto:trunk_v8?expand=1

Thank you for the patch. I just commented on it. Feel free to open a pull request or send a patch ;-) http://multipath-tcp.org/pmwiki.php/Developer/SubmitAPatch

**Comment by teto** [comment]
thanks for the comment I will send it on the mailing list. 

I remembered reading sthg about localhost specific behavior, thanks for reminding me.
I am running the netlink pm but the behavior is similar and is not fun when I wnat to test things.
Found the culprit thanks for your intel :
```
	if (ifa->ifa_scope > RT_SCOPE_LINK ||
	    ipv4_is_loopback(ifa->ifa_local))
		return;

```

**Comment by matttbe** [comment]
> I am running the netlink pm but the behavior is similar and is not fun when I wnat to test things.

You might need to modify `mptcp_doit()`: https://github.com/multipath-tcp/mptcp/blob/mptcp_trunk/net/mptcp/mptcp_ctrl.c#L1981

But maybe better to setup two KVM to do your tests.
